### ISSUE TITLE
Question: Login with browser and export cookies to...

### ISSUE THREAD

**Issue by xDShot** [Sude-/lgogdownloader#110]
`Login with browser and export cookies to "/home/xdshot/.config/lgogdownloader/cookies.txt"`

Which exactly cookies do I need to get from my web browser? And how should I paste them into cookies.txt file?

**Comment by Sude-** [comment]
Currently my cookies.txt contains these cookies
```
galaxy-login-s
galaxy-login-al
galaxy-login-tsa
gog_us
gog_lc
cart_token
gog-al
gog_verify
```
For Firefox you can use any cookie export add-on that exports cookies in netscape format
https://addons.mozilla.org/en-US/firefox/search/?q=cookie+export
Other browsers should have similar add-ons

**Comment by xDShot** [comment]
Thanks
