### ISSUE TITLE
Timestamps on downloaded files

### ISSUE THREAD

**Issue by shakeyourbunny** [Sude-/lgogdownloader#111]
I took the liberty to report the suggestion from eiii @ GOG forum thread:
https://www.gog.com/forum/general/lgogdownloader_gogdownloader_for_linux/post921

He suggested that the timestampe of downloaded files should receive the original timestamp and not the time/date of the downloading.

In addition, existing, correctly downloaded files should be touched with the correct timestamps from GOG.

**Comment by Sude-** [comment]
6b8d5ff makes the downloader preserve timestamps and retroactively change them for previously downloaded files
