### ISSUE TITLE
Man page excludes linux platform

### ISSUE THREAD

**Issue by step21** [Sude-/lgogdownloader#120]
Per this thread (https://www.reddit.com/r/linux_gaming/comments/6uk60b/looks_like_gog_galaxy_wont_come_to_linux_any_time/dlthefu/) I was told that some people got confused by lgogdownloaders manpage, which more or less seems to imply that only the download of windows and mac versions is supported. Maybe this could be easily changed.

**Comment by Sude-** [comment]
Fixed in 638590c

**Comment by step21** [comment]
Thanks :)
