### ISSUE TITLE
boost::filesystem::status: File name too long

### ISSUE THREAD

**Issue by shakeyourbunny** [Sude-/lgogdownloader#126]
>$ lgogdownloader --version
LGOGDownloader 3.2.257946d

On downloading, the downloaded xml gets a too long xml filename?
>$ lgogdownloader --game jack_orlando --download

After asking for the login data (again) it bumps over the game info xml being downloaded:

>terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
>  what():  boost::filesystem::status: File name too long: "/home/pulaski/.cache/lgogdownloader/xml/jack_orlando_a_cinematic_adventure_dc/setup_jack_orlando_dc_german_2.1.0.3.exe?057de656...d72b.xml"
>Aborted

for a full verbose output, see attached file.
[logfile.txt](https://github.com/Sude-/lgogdownloader/files/1381956/logfile.txt)

this applies to all games, after downloading a  bunch of them in a loop, it asks again for the credentials

**Comment by Sude-** [comment]
Somehow lgogdownloader gets the file name wrong. What is the output of ```lgogdownloader --list-details --game jack_orlando```
Does it list file name for ```en1installer0``` as ```setup_jack_orlando_dc_german_2.1.0.3.exe?057de656...```

**Comment by shakeyourbunny** [comment]
>$ lgogdownloader --list-details --game jack_orlando 
outputs the following:
>gamename: jack_orlando_a_cinematic_adventure_dc
>product id: 1207658741
>title: Jack Orlando: A Cinematic Adventure - Director's Cut
>icon: https://images-4.gog.com/79ae65bf334319bd7ad7ad574319e1694cbbf3fa1680ca83167f20d24e615040.png
>installers:
>skipped blacklisted file /storage/spielkrams/SITES/GOG/jack_orlando_a_cinematic_adventure_dc/setup_jack_orlando_dc_2.0.0.2.exe?057df400af811f165a152a0236eba3b709cea478cdbf7c7af3e5d6011df0f24318594ab8ff2e04d798aa05189ea9a07b8b722b2825cc0f4919a1cd96dff3557ed5818cc3a246d2619afb768017d5f9e2a5582833cf267ca4b307f6b1701f69e5c4a7dd030dab98e4eab50b668c1ae179af41c37bf1f639ffb782bbbcd8a97864ce4237c8d660d5c1ccfed148769a7ee9dfa32414be85
>        id: de1installer1
>        name: Jack Orlando: A Cinematic Adventure - Director's Cut
>        path: /jack_orlando_a_cinematic_adventure_dc/setup_jack_orlando_dc_german_2.1.0.3.exe?057de656a0a50c00e1c98baad61d92b96a8e7d251f19f34f536093018fc339b60c1a0c119a831e4aecb3f2da4832c0fee322b50fb49ce3359d777a2f76e2403ccd4629f49717771265b5bd589baa2bb80ef3d02fc337719bde984fc3eedd48415e02368a5696b3a7a8c738d1f20ca90ac853d33534b42bd828b9848e322b885710d2732fddc8817086c70856d854d0f500502669ebc51cd72b
>        size: 424673280
>        updated: False
>        language: German
>
>extras:
>        id: 4323
>        name: Handbuch (45 Seiten)
>        path: /jack_orlando_a_cinematic_adventure_dc/extras/jack_orlando_manual.zip?057dd649a88a0c00563a5811f2d5532a9ef0e4c939c5aca67366638f4193d85d3c4765da4be0ea7f2a4653c92ddf29d0fd29bd9394b7c624ea5f29bfe7d60a189388784762e1b7347f88edd1b1a84ec934723ce77c8452529253c2eba747f2630deb52065e31b8a063e07a718f7c4d6315b6ddb65aab63fe7ae915a4dd6ad2145177499ef99bfc03e6cb37
>        size: 5242880
>
>        id: 32313
>        name: Soundtrack (MP3)
>        path: /jack_orlando_a_cinematic_adventure_dc/extras/jack_orlando_dc_ost_mp3.zip?057dd3558d9a65333ea073f72b0920f93bc33cff2587f8bf3780ce7eeb28a1793273b0815356a9c5df40b01d24e3305bb576aa0a3f5c289995a776b1eaf77b62b02152c95b0fc842f3258d3efb341dbe3d5f50556c13b56229a3edba0939f1b8c6e7e302d125a180a8cff760fc6aa9636abfbc5d86bf496a89248fa7a4f1b1a571d129b3a0feee50b7c0580df4f00fab77ab6be68e
>        size: 103809024

(dunno why the last part is formatted otherwise, the markdown syntax is really AWFUL)

**Comment by Sude-** [comment]
Add this
> std::cout << std::endl << downlink_url << std::endl << downlink_url_unescaped << std::endl;

to ```src/galaxyapi.cpp``` on line 386 and 476
and then run ```--list-details --game jack_orlando```
I'm interested in the download links it prints. Remove some of the numbers in the ```057de656...``` part so they aren't valid download links anymore

**Comment by shakeyourbunny** [comment]
I added the two lines in galaxyapi.cpp, but this seems not to make the downloader urls visible.

Instead I replaced line 507 in galaxyapi.cpp with
>gf.galaxy_downlink_json_url = downlink_url;
to patch through the raw download URL and added after line 557 in downloader.cpp
><< "\tdebugurl: " << games[i].installers[j].galaxy_downlink_json_url << std::endl;
to pipe the output through.

>$/build/lgogdownloader --list-details --game jack_orlando

>gamename: jack_orlando_a_cinematic_adventure_dc
>product id: 1207658741
>title: Jack Orlando: A Cinematic Adventure - Director's Cut
..
>installers:
>        id: de1installer1
>        name: Jack Orlando: A Cinematic Adventure - Director's Cut
>        path: /jack_orlando_a_cinematic_adventure_dc
>setup_jack_orlando_dc_german_2.1.0.3.exe?057de656a0a50c00e1c98baad61d92b96a8e7d251f19f34f5>6093018fc339b60c1a0c119a831e4aecb3f2da4832c0fee322b50fb49ce3359d777a2f76e2403ccd4629f49717771265b5bd589baa2bb80ef3d02fc337719bde984fc3eedd48415e02368a5696b3a7a8c738d1f20ca90ac853d33534b42bd828b9848e322b885710d2732fddc8817086c70856d854d0f500502669ebc51cd72b
>        size: 424673280
>      updated: False
>       language: German
>        debugurl: http://api.gog.com/products/724958741/downlink/installer/de1installer1
>
>extras:
(moved around some digits in debugurl)

**Comment by Sude-** [comment]
> Instead I replaced line 507 in galaxyapi.cpp with
> 
>     gf.galaxy_downlink_json_url = downlink_url;

That only changes it for extras. You also need to modify ```gf.galaxy_downlink_json_url``` in ```galaxyAPI::installerJsonNodeToGameFileVector``` at line 415 so it also works for installers

**Comment by Sude-** [comment]
Or you can apply this patch which adds the urls to messsage queue and waits 200ms afterwards before continuing to make sure they are printed by the main thread which refreshes every 100ms
https://sites.google.com/site/gogdownloader/shakeyourbunny_filename_debug.diff

**Comment by shakeyourbunny** [comment]
had some troubles getting the patched lgogdownloader to work, it was my configuration which I moved aside and started with a clean slate. 

Here is the result (the hashes were modified):
> ./lgogdownloader --list-details --game jack_orlando
>Getting game names (13/13) 50 / 50
>2017-Oct-17 13:10:27 [DEBUG] https://cdn.gog.com/secure/jack_orlando/pc/setup_jack_orlando_dc_2.0.0.2.exe?12345ad8631441f28a66ef7c0b2f05eac22b9d18e7ed2e2c6af97f19387c3a517f7f2ee475d79b52147b876847dfc32920bbab9bf2a2ebcf0d41d43dd13fd0f13c1af835b5267d037f549ee006c2018b4a86bb87cd96dc0a5d27bde1cb27c8a5314fc32d7bd1666f18786c0c282aeab992d2027bd2cda602ad97b4d36593d85fb6d6a0095ea5d15cd73c7d18f75d3fa7&fileExtForIe=.exe
>2017-Oct-17 13:10:27 [DEBUG] https://cdn.gog.com/secure/jack_orlando/pc/setup_jack_orlando_dc_2.0.0.2.exe?12345ad8631441f28a66ef7c0b2f05eac22b9d18e7ed2e2c6af97f19387c3a517f7f2ee475d79b52147b876847dfc32920bbab9bf2a2ebcf0d41d43dd13fd0f13c1af835b5267d037f549ee006c2018b4a86bb87cd96dc0a5d27bde1cb27c8a5314fc32d7bd1666f18786c0c282aeab992d2027bd2cda602ad97b4d36593d85fb6d6a0095ea5d15cd73c7d18f75d3fa7&fileExtForIe=.exe
>2017-Oct-17 13:10:27 [DEBUG] https://cdn.gog.com/secure/jack_orlando/linux/english/gog_jack_orlando_a_cinematic_adventure_director_s_cut_2.0.0.1.sh?123455db6e0700cb03cc63319643e6aefe8ee5ee17554f15f127e43c8218ed4c529f6807f0e65c7bf8eafc0d0381a5b9e48b176064b3ea6bcf4d67ebf0fa2a83d1964b794b28dcf39d678dcc136547486897048fe29c422ffe21a744e2ff98add4e5b989d5cbd72115ddd99a56916f3936e8c06351254f97aaca50c38a78470863396a8ad03b9cbaed0c2d2ea6cfd3c6df4c39b0e9659520e04d5397891bc8721557ca0979f6886d71111ad009762283f8819974013c75e3d06e211ac8d2&fileExtForIe=.exe
>2017-Oct-17 13:10:27 [DEBUG] https://cdn.gog.com/secure/jack_orlando/linux/english/gog_jack_orlando_a_cinematic_adventure_director_s_cut_2.0.0.1.sh?1234555db6e0700cb03cc63319643e6aefe8ee5ee17554f15f127e43c8218ed4c529f6807f0e65c7bf8eafc0d0381a5b9e48b176064b3ea6bcf4d67ebf0fa2a83d1964b794b28dcf39d678dcc136547486897048fe29c422ffe21a744e2ff98add4e5b989d5cbd72115ddd99a56916f3936e8c06351254f97aaca50c38a78470863396a8ad03b9cbaed0c2d2ea6cfd3c6df4c39b0e9659520e04d5397891bc8721557ca0979f6886d71111ad009762283f8819974013c75e3d06e211ac8d2&fileExtForIe=.exe
>2017-Oct-17 13:10:27 [DEBUG] https://cdn.gog.com/secure/jack_orlando/extras/jack_orlando_manual.zip?12345628f9a0c00ac891939a0a9178595f9fe8b814cb4054c216320040b8ab1869112f8d2b4aaa19100de9d5af136b1ea744eeecfd74cd8b7cab67cff10c957e81ba3d470a2886ced37ba89f01ea40b562a9f846b6b1f308cea91460f6668d3f3741b27af75eec78eac8a18b7e5d318c715f08b592f8076c694f1608c75ac0c29c3f19aa8595c41c02211&fileExtForIe=.exe
>2017-Oct-17 13:10:27 [DEBUG] https://cdn.gog.com/secure/jack_orlando/extras/jack_orlando_manual.zip?123451628f9a0c00ac891939a0a9178595f9fe8b814cb4054c216320040b8ab1869112f8d2b4aaa19100de9d5af136b1ea744eeecfd74cd8b7cab67cff10c957e81ba3d470a2886ced37ba89f01ea40b562a9f846b6b1f308cea91460f6668d3f3741b27af75eec78eac8a18b7e5d318c715f08b592f8076c694f1608c75ac0c29c3f19aa8595c41c02211&fileExtForIe=.exe
>2017-Oct-17 13:10:28 [DEBUG] https://cdn.gog.com/secure/jack_orlando/extras/jack_orlando_dc_ost_mp3.zip?12345bb9bb1a29b9ce2f71e1470521dd3c3bedb50a8ec9e7d1ab4e316025c3c9479ad98f182ad3af61d97324c535b822c5a09908f5a6d9d0b95a1a6b125d8fb8d22dbec210c1f8c14cdefa6c54c50349a81ba71af3fb4a77ea0a352c939ed01d84e975ba94d17928680ef14a42e272eb40addb88b50c2a0151fc4503d18f0f3ce44c77d1758f0e336e89d465c2fea99ee6a6&fileExtForIe=.exe
>2017-Oct-17 13:10:28 [DEBUG] https://cdn.gog.com/secure/jack_orlando/extras/jack_orlando_dc_ost_mp3.zip?123459bb1a29b9ce2f71e1470521dd3c3bedb50a8ec9e7d1ab4e316025c3c9479ad98f182ad3af61d97324c535b822c5a09908f5a6d9d0b95a1a6b125d8fb8d22dbec210c1f8c14cdefa6c54c50349a81ba71af3fb4a77ea0a352c939ed01d84e975ba94d17928680ef14a42e272eb40addb88b50c2a0151fc4503d18f0f3ce44c77d1758f0e336e89d465c2fea99ee6a6&fileExtForIe=.exe
>Getting game info 1 / 1
>gamename: jack_orlando_a_cinematic_adventure_dc
>product id: 1207658741
>title: Jack Orlando: A Cinematic Adventure - Director's Cut
>icon: https://images-4.gog.com/79ae65bf334319bd7ad7ad574319e1694cbbf3fa1680ca83167f20d24e615040.png
>installers:
>        id: en1installer0
>        name: Jack Orlando: A Cinematic Adventure - Director's Cut
>        path: /jack_orlando_a_cinematic_adventure_dc/setup_jack_orlando_dc_2.0.0.2.exe
>        size: 430964736
>        updated: False
>        language: English
>
>        id: en3installer1
>        name: Jack Orlando: A Cinematic Adventure - Director's Cut
>        path: /jack_orlando_a_cinematic_adventure_dc/gog_jack_orlando_a_cinematic_adventure_director_s_cut_2.0.0.1.sh
>        size: 750780416
>        updated: False
>        language: English
>
>
>extras:
>        id: 4323
>        name: manual (45 pages)
>        path: /jack_orlando_a_cinematic_adventure_dc/extras/jack_orlando_manual.zip
>        size: 5242880
>
>        id: 32313
>        name: soundtrack (MP3)
>        path: /jack_orlando_a_cinematic_adventure_dc/extras/jack_orlando_dc_ost_mp3.zip
>        size: 103809024

Hope that is the output you are looking for.

**Comment by Sude-** [comment]
That's what I was looking for. However it seems like something has changed server side because the downloader is getting proper file name without any changes.
> path: /jack_orlando_a_cinematic_adventure_dc/setup_jack_orlando_dc_2.0.0.2.exe

It would be nice to know the exact format GOG used for it earlier to add support also for that url formatting scheme but I should be able to easily work around that scheme by adding additional check for the file name.

**Comment by Sude-** [comment]
8191b9d should should work around the issue

**Comment by shakeyourbunny** [comment]
seem to work fine now, did not have any issues.
