### ISSUE TITLE
Galaxy: Login failed

### ISSUE THREAD

**Issue by Protarios** [Sude-/lgogdownloader#132]
Whenever I try to login I get a:

```
Email: mail@...
Password: 
Couldn't resolve host name
HTTP: Login successful
Galaxy: Login failed
```

If I try the --login-api flag, the same thing only an additional loop:

```
Email: mail@...
Password: 
API: Login successful
Email: mail@...
Password: 
Couldn't resolve host name
HTTP: Login successful
Galaxy: Login failed
```

**Comment by WhyNotHugo** [comment]
I've been having this issue for weeks now. Is it possible that something else can cause it, other than an error on gog's side?
