### ISSUE TITLE
Add operating system to the user agent

### ISSUE THREAD

**Issue by shmerl** [Sude-/lgogdownloader#135]
Currently lgogdownloader sets user agent to something like `LGOGDownloader <version>` which is not enough for GOG to detect the operating system of the originating request using their common methods (in theory you can build lgogdownloader for any OS). May be adding OS to it can be helpful for download statistics.

See [here](https://www.reddit.com/r/linux_gaming/comments/8unssh/is_there_any_way_to_indicate_my_os_when_buying/e1h5pfk/).

**Comment by Sude-** [comment]
I've changed the default user agent in 9dc5d41 to
```LGOGDownloader/${VERSION_NUMBER} (${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR})```
which should produce user agent string like
```LGOGDownloader/3.3.9dc5d41 (Linux x86_64)```

**Comment by shmerl** [comment]
Sounds great! I'll ping GOG developers about it.
