### ISSUE TITLE
Hidden games are not downloaded/shown in status

### ISSUE THREAD

**Issue by glhez** [Sude-/lgogdownloader#141]
I have finished several games and I hide them in my GOG list, for example: baldurs_gate_2_complete setup_baldurs_gate2_2.0.0.12.exe

When hidden, I've got 77 files downloaded by lgogdownloader (v3.4 on gentoo).
When not hidden, I've got 98 files.

I am not hiding them to disable download: I simply don't want them to appear in my gamelist in Galaxy.

Is there a way to tell lgogdownloader to download/list/status those file as well ?

As a workaround, I've removed the hidden status.

**Comment by Sude-** [comment]
It's not possible to download hidden products with lgogdownloader at the moment.
However it should be fairly easy to implement option to download those.
This should only need few changes to Website::getGames() function and adding a command line option to toggle the behavior.

**Comment by Sude-** [comment]
df628b2 adds option ```--include-hidden-products``` that can be used to list and download hidden products
