### ISSUE TITLE
lgogdownloader hangs when trying to download the Witcher 3 GOTY

### ISSUE THREAD

**Issue by shmerl** [Sude-/lgogdownloader#142]
The game is already downloaded, and I expected it to check files and exit. But it simply hangs like this:

![lgogdownloader_hang](https://user-images.githubusercontent.com/310927/49691874-f5b78780-fb19-11e8-889a-284a6e62ae4b.png)

Using lgogdownloader packaged in Debian (3.4-1+b1).

**Comment by Sude-** [comment]
Not sure why this happens. I haven't been able to reproduce this on my system.
I might have to install Debian in virtual machine to see if I can reproduce this.

**Comment by shmerl** [comment]
This is still happening (with 3.4-2 as well).

**Comment by shmerl** [comment]
It's not happening anymore, so I'll close this.
