### ISSUE TITLE
Invalid disconnections due to lowspeed handling

### ISSUE THREAD

**Issue by danielnelson** [Sude-/lgogdownloader#147]
I'm receiving frequent disconnections (every 30s) when downloading my collection.  I enabled `--curl-verbose` and saw:
```
* Operation too slow. Less than 200 bytes/sec transferred the last 30 seconds
* stopped the pause stream!     
```

However, my download speed was much higher than this, closer to 3MB/s.  In `~/.config/lgogdownloader/config.cfg` I set the `lowspeed-rate` value to 0, and this seems to have stopped the disconnections:
```diff
- lowspeed-rate = 200
+ lowspeed-rate = 0
```

I'm using lgogdownloader 3.5 from Gentoo with USE=-gui

**Comment by lel-amri** [comment]
I have the same issue on Gentoo. I suspect libcurl is at fault because the parameters passed to curl by lgogdownloader are ok. I found this bug-report that confirms this: https://github.com/curl/curl/issues/3927

**Comment by danielnelson** [comment]
Thanks for the tip @lel-amri, I rebuilt with curl 7.65.1 and it did indeed solve the issue for me.
