### ISSUE TITLE
Metadata are not downloaded for older files

### ISSUE THREAD

**Issue by TheFrenchGhosty** [Sude-/lgogdownloader#153]
When I made my [script](https://gitlab.com/TheFrenchGhosty/TheFrenchGhostys-GOG-Archivist-Scripts) I used it, then [after some times](https://gitlab.com/TheFrenchGhosty/TheFrenchGhostys-GOG-Archivist-Scripts/commit/05752b2ee9add83b00360e9dd775db8afbdd8877) I added ``--xml-directory`` to have the metadata with the files.

The problem is that, only the metadata of the files downloaded after this setting was added are stored, and every files that has been downloaded before will never have their metadata stored.

In my opinion it should be handled like how changelogs are handled, and downloaded every time the script is run.

**Comment by Sude-** [comment]
The problem is that the downloader skips to next file right after it determines the file it tries to download is already complete.
00df6d6 should fix this by saving the xml data before skipping to next file

**Comment by TheFrenchGhosty** [comment]
Working perfectly, amazing!

Thanks a lot for this fix and obviously for this amazing tool!
