### ISSUE TITLE
"check-orphans" will report non-english files as orphan

### ISSUE THREAD

**Issue by TheFrenchGhosty** [Sude-/lgogdownloader#161]
```--check-orphans``` will report every files that are not english as orphan if a ```config.cfg``` file doesn't mention that the user want multiples languages (a workaround is to have a ```config.cfg``` file mentioning it).

```--check-ophans``` is supposed to "check for orphaned files (files found on local filesystem that are not found on GOG servers)" (from ```--help```) yet those existing files are reported as orphan.

Output example: 

```
./the_witcher_3_wild_hunt_game/languagepacks/witcher3_lang_fr_2.0.0.52.exe
./the_witcher_3_wild_hunt_game/languagepacks/witcher3_lang_fr_2.0.0.52-1.bin
```

**Comment by Sude-** [comment]
56a0613 should fix this issue
