### ISSUE TITLE
some games missing

### ISSUE THREAD

**Issue by 0-wiz-0** [Sude-/lgogdownloader#162]
I tried to keep an overview of what I have with
````
lgogdownloader --list-details --language all --platform all --ignore-dlc-count .
````
recently that stopped working correctly.

Now I have some entries twice, e.g.
````
gamename: alien_nations
        path: /alien_nations/setup_alien_nations_2.05_hotfix_(21104).exe
        path: /alien_nations/setup_alien_nations_2.05_hotfix_(french)_(21104).exe
        path: /alien_nations/setup_alien_nations_2.05_hotfix_(german)_(21104).exe
        path: /alien_nations/extras/alien_nations_manual.zip
        path: /alien_nations/extras/alien_nations_wallpaper.zip
        path: /alien_nations/extras/alien_nations_soundtrack.zip
gamename: alien_nations
        path: /alien_nations/setup_alien_nations_2.05_hotfix_(21104).exe
        path: /alien_nations/setup_alien_nations_2.05_hotfix_(french)_(21104).exe
        path: /alien_nations/setup_alien_nations_2.05_hotfix_(german)_(21104).exe
        path: /alien_nations/extras/alien_nations_manual.zip
        path: /alien_nations/extras/alien_nations_wallpaper.zip
        path: /alien_nations/extras/alien_nations_soundtrack.zip
````
but others are missing, e.g. dark_queen_of_krynn or all heroes of might and magic games.

I guess it could be a bug on the server side, but on the GOG webpage the games are listed correctly. The count is correct, i.e. 24 are duplicate and 24 are missing.

**Comment by Sude-** [comment]
Does ```--list``` show the missing games?

**Comment by 0-wiz-0** [comment]
I just tried `--list` and got 14 less games than I have, of which another 35 were listed duplicately, so 49 games were missing completely.

**Comment by 0-wiz-0** [comment]
I have a rather large collection (> 2000 games), perhaps that's why other people don't see this issue? Is there a bug report I can file at GOG about this, what should I say there?

**Comment by Sude-** [comment]
Lets see if the json response from server has duplicates before lgogdownloader tries to parse it.

Are there duplicates in the output of this:
```curl --cookie ~/.config/lgogdownloader/cookies.txt  "https://www.gog.com/account/getFilteredProducts?hiddenFlag=0&isUpdated=0&mediaType=1&sortBy=title&system=&page=1" -o - | json_pp | grep slug```

```json_pp``` should be part of ```perl``` or ```libjson-pp-perl``` package

**Comment by 0-wiz-0** [comment]
That particular command gives me 100 different games (but of course, I have 20 more pages...). So I tried:
````
for i in $(seq 1 22); do curl --cookie ~/.config/lgogdownloader/cookies.txt "https://www.gog.com/account/getFilteredProducts?hiddenFlag=0&isUpdated=0&mediaType=1&sortBy=title&system=&page="$i -o -  | json_pp | grep slug > $i.txt; done
````
and see
````
$ cat *txt | wc -l
    2175
$ cat *txt | sort -u | wc -l
    2175
````
so this looks ok. Is `lgogdownloader` downloading them all directly after one another, or are there perhaps pauses in between that makes GOG re-sort them?

**Comment by Sude-** [comment]
lgogdownloader should download them directly after one another unless ```--wait``` is used.
The result makes me think that something goes wrong when lgogdownloader is parsing the json reponse.

Enable debug info printing by building lgogdownloader with ```cmake .. -DCMAKE_CXX_FLAGS="-DDEBUG=1"```
This makes it print the json response to stderr.

Redirect stderr output to file and see if there are duplicates
```
$ ./lgogdownloader --list 2> debug.txt
$ grep "\"slug\"" debug.txt | sort
```

**Comment by 0-wiz-0** [comment]
Right now this looks good:
````
# grep "\"slug\"" debug.txt | sort | wc -l
    2171
# grep "\"slug\"" debug.txt | sort -u | wc -l
    2171
````
Comparing it with the curl output from above: the grep above was not good enough and also matched the four metal slug games "url" entries, so it matches the curl output.

**Comment by Sude-** [comment]
So it gets valid info but something goes wrong with it later.

Try adding this after line 275 in ```src/website.cpp```
```
std::cerr << "game.name = " << game.name << std::endl;
```
and check if the amount of games matches the previous output from curl
```
$ lgogdownloader --list 2> debug.txt
$ grep "game\.name" debug.txt | sort -u | wc -l
```

**Comment by shakeyourbunny** [comment]
I checked this out too with my library; my GOG library on https://www.gog.com/account says that I have 1855 games.

OS: CentOS Linux release 8.1.1911 (Core), Boost 1.66

curl:
````
$ for i in $(seq 1 19); do curl --cookie ~/.config/lgogdownloader/cookies.txt "https://www.gog.com/account/getFilteredProducts?hiddenFlag=0&isUpdated=0&mediaType=1&sortBy=title&system=&page="$i -o -  | json_pp | grep slug > $i.txt; done
$ cat *.txt | wc -l
1959
$ cat *txt | sort -u | wc -l
1866
````

lgogdownloader (debug build):
````
$ lgogdownloader --version
LGOGDownloader 3.5.0a7648d
$ lgogdownloader --list 2> debug.txt
$ grep "\"slug\"" debug.txt | sort | wc -l
1855
$ grep "\"slug\"" debug.txt | sort -u | wc -l
1855
````

the patched debug executable is currently running, will add this information, as it is finished.

**Comment by 0-wiz-0** [comment]
Something went wrong:
````
diff --git a/src/website.cpp b/src/website.cpp
index a83fe44..46b9f17 100644
--- a/src/website.cpp
+++ b/src/website.cpp
@@ -273,6 +273,7 @@ std::vector<gameItem> Website::getGames()
                     }
                 }
                 games.push_back(game);
+               std::cerr << "game.name = " << game.name << std::endl;
             }
         }
         i++;
````
and then:
````
lgogdownloader --list 2> debug2.txt
````
gives me only ~80kB:
````
Getting game names (1/22) 1 / 100
...
Getting game names (22/22) 71 / 71
````

**Comment by Sude-** [comment]
I forgot that the progress info printing on [line 174](https://github.com/Sude-/lgogdownloader/blob/master/src/website.cpp#L174) manipulates the cursor position.
You should either change line 174 to use ```std::cout``` instead of ```std::cerr``` and use the previous command to redirect stderr to file
```
lgogdownloader --list 2> debug.txt
```
or use ```std::cout``` for the debug info printing on line 275 and redirect stdout to file
```
lgogdownloader --list > debug.txt
```

**Comment by 0-wiz-0** [comment]
Hm, looks good:
````
# grep "game\.name" debug3.txt | sort -u | wc -l
    2171
````

**Comment by 0-wiz-0** [comment]
It's currently working again, let's assume it was server-side.
