### ISSUE TITLE
& breaks filename

### ISSUE THREAD

**Issue by ScarletEmerald** [Sude-/lgogdownloader#164]
Recently lgogdownloader has been downloading the file
the_witcher_2/extras/The_Witcher_2_pamphlet_
Previously it was downloading
the_witcher_2/extras/The_Witcher_2_pamphlet_&_envelope.zip
It looks like the & is breaking the filename.  I did not update lgogdownloader, so either something on my system or the GOG server must have changed.  (I confirmed this still happens with the latest version.)  Is anyone else having this issue?

I am running Debian bullseye and building lgogdownloader from source.

**Comment by zahroc** [comment]
Confirmed here also running Ubuntu 18.04.3 LTS under WSL Windows 10 1909 Build 18363.657 and lgogdownloader v3.5. 

I also noticed tonight the following orange message when running for various items: 2020-Feb-27 22:02:13 [Thread #0] Download complete (HTTP response code said error): zork_anthology_calendar.zip

**Comment by Sude-** [comment]
There was an issue with detecting the file name from downlink url when it contained ampersand
This should be fixed in 6522247
It also fixes an issue with ```--download-file``` failing to assign proper filename automatically

**Comment by zahroc** [comment]
Verified fixed here with witcher files.

**Comment by ScarletEmerald** [comment]
Looks good for me too, thanks for the fix!
