### ISSUE TITLE
Add bigger units on download status

### ISSUE THREAD

**Issue by shakeyourbunny** [Sude-/lgogdownloader#165]
Would it be possible to switch in the  download status from MB to GB (and then to TB) if a certain threshold (say, 10000 MB -> GB, 1000 GB -> TB ) is met?

>#1 Star_Control_1+2_manuals.zip    
>100% [==========================] 1.46/1.46MB @ 0.00kB/s ETA: 0s  
>#2 Star_Control_2_soundtrack.zip 
>100% [==========================] 75.98/75.98MB @ 0.00kB/s ETA: 0s                                                    
> ...                                               
>Total: 21.23MB/s | Remaining: 2533 (1317042.00MB) ETA: 17h 16m 32s 

So it would read 1,2 TB (1317042.00 / 1024 ~ 1286 GB -> TB) instead to download.
Would be really nice, especially for people who have bigger libraries on GOG.

**Comment by Sude-** [comment]
985696f makes the downloader automatically select appropriate size unit for total remaining up to PB
