### ISSUE TITLE
Issues with & in names

### ISSUE THREAD

**Issue by 0-wiz-0** [Sude-/lgogdownloader#166]
Some files now have "&" (ampersands) in their paths, and this is not handled correctly.
For example,
````
lgogdownloader --list-details --language all --platform all --ignore-dlc-count .
````
contains
````
the_witcher_2/The_Witcher_2_pamphlet_
````
which should be
````
the_witcher_2/The_Witcher_2_pamphlet_&_envelope.zip
````

This also affects at least sensible_soccer_2006.

**Comment by Sude-** [comment]
Are you using the latest git version?
6522247 should have fixed that

**Comment by 0-wiz-0** [comment]
No, I didn't have that yet. I assume it'll fix it, thanks!
