### ISSUE TITLE
Doesn't connect any more.

### ISSUE THREAD

**Issue by paulscottrobson** [Sude-/lgogdownloader#176]
Hi, as I suspect you may know, lgogdownloader no longer works. On my version (3.7 64 bit Arch) you get a "URL using bad/illegal format or missing URL" after entering the password. 

I notice the (removed forty curse words seven of which are illegal) stupid pictorial captcha is back again and I suspect this is something to do with it, though I did try building it with QT installed and it didn't seem to help. I did try it on Ubuntu from a USB key and that didn't work either (the Ubuntu one has it built in).

**Comment by chungy** [comment]
Are you entering the correct password? I've just tried lgogdownloader and it's still fully functional for me.

**Comment by paulscottrobson** [comment]
Yep. It seems to be the case that GOG stick their stupid captcha in sometimes and sometimes they don't, which may be why yours works and mine doesn't. It used to work fine up until yesterday (which was the same time the captchas started appearing)

**Comment by yourfate** [comment]
I have the same error on FreeBSD 12.1.

I compiled v3.7.

I sometimes also get "couldn't resolve host name" even though I can resolve gog.com just fine on that machine.
