### ISSUE TITLE
option to list details of only one game

### ISSUE THREAD

**Issue by Lukas1818** [Sude-/lgogdownloader#185]
If you have bought some games, the details list can be very long. It would be very nice if this would be possible:
```
$ gogdownloader --list-details space_haven
```
and
```
$ gogdownloader --list-details 1115004086
```

**Comment by Sude-** [comment]
Already possible using regex with `--game` option
`lgogdownloader --list-details --game ^space_haven$`

**Comment by Lukas1818** [comment]
Thanks for the fast answer.
I did not know this was possible and I did not find it in the documentation.
