### ISSUE TITLE
current version requires libboost 1.75.0.

### ISSUE THREAD

**Issue by weatherroll** [Sude-/lgogdownloader#197]
After updating libboost, won't run lgogdownload. Even if using links to 1.76.0, will give an error about a symbol.

**Comment by itoijala** [comment]
What system are you on?

On Arch Linux using boost 1.76.0-1, lgodownloader runs fine after a clean rebuild from git.

**Comment by weatherroll** [comment]
Artix Linux 
5.12.8-artix1-1

**Comment by weatherroll** [comment]
Following your instructions work. Not sure why installing it using yay didn't work. Just gitcloned the aur.
