### ISSUE TITLE
Download CD Keys as well

### ISSUE THREAD

**Issue by grossmaul** [Sude-/lgogdownloader#201]
I got games like "the_settlers_3_ultimate_collection" which requires a key for installation. In the library on GOG you click on the game, then on "More" -> "CD-keys". There you can access the key.

It's important that the LGOGdownloader can download those keys too, otherwise the game is storage waste... (or you save all keys manually afterwards)

**Comment by ssokolow** [comment]
It should already be doing that and saving a `serials.txt` file. Did that break?

**Comment by grossmaul** [comment]
I can ` lgogdownloader --language de+en --threads 8 --download` which downloaded me all games in German and English. And in the folger `the_settlers_3_ultimate_collection` there is no `serials.txt`... Neither in the extras folder as well

**Comment by Marauder1024** [comment]
Add the --save-serials flag.

**Comment by grossmaul** [comment]
Oh okay, I didnt see that when checking the command list. Thank you :)
