### ISSUE TITLE
XML parsing error as of 2022-02-14.

### ISSUE THREAD

**Issue by racofer** [Sude-/lgogdownloader#214]
According to other user reports [at the gogrepo thread](https://www.gog.com/forum/general/gogrepopy_python_script_for_regularly_backing_up_your_purchased_gog_collection_for_full_offline_e/page144) over at GOG forums, XML parsing is no longer working.

I have tried to update my library today and every game is now throwing XML parsing failed messages, which in turn causes lgogdownloader to redownload game files when running a repair action.

**Comment by racofer** [comment]
Strangely, some games appear to be working now. Cyberpunk is still failing to parse XML data for all of its file, same thing for Arma.

I will test tomorrow with my entire library to see what's working and what isn't.

**Comment by Sude-** [comment]
It seems that GOG changed something and now the server sometimes responds with gzip compressed XML data
30f6988 should fix the issue

**Comment by racofer** [comment]
Thanks! It appears everything is now working as before.
