### ISSUE TITLE
Is it possible to skip games?

### ISSUE THREAD

**Issue by maluramichael** [Sude-/lgogdownloader#223]
My library is pretty big and some games, for example cyberpunk are a couple of 100gb big. Is it possible to exclude a number of games from downloading?

**Comment by maluramichael** [comment]
I solved my problem with a workaround. I update the cache before i download any content. See https://gist.github.com/maluramichael/31dc56cfc28bb65a2e8157319f6b5d39

**Comment by shakeyourbunny** [comment]
The more official way to do is to create the blacklist file "blacklist.txt" in $HOME/.config/lgogdownloader.

This accepts regular expressions to ignore games (and other stuff). In your case, ignoring Cyberpunk 2077 would be placing there:
````
Rp /cyberpunk_2077/.*
````

If you don't like certain file formats, put this in:
````
### no other music formats except mp3:
Rp .*_flac\.zip
Rp .*_FLAC\.zip
Rp .*_flac_rev\.zip
Rp .*_flac_final\.zip
Rp .*_wav\.zip
Rp .*_wave\.zip
Rp .*_ogg\.zip
````

**Comment by maluramichael** [comment]
Perfect. Did not search for blacklist. Only for skip :) Thank you
