### ISSUE TITLE
Feature: json output for --list-details

### ISSUE THREAD

**Issue by LuckyTurtleDev** [Sude-/lgogdownloader#235]
It would be nice to have an option to enable json output for `lgogdownloader --list-details`.

**Comment by LuckyTurtleDev** [comment]
thanks for the fast update, but sadly it seems not to work:
```
lgogdownloader --list-format j
LGOGDownloader 3.9.9e49b6f
Options:

  -h [ --help ]                         Print help message
...
```
I have also tried to `json` or `n` instead of `j`, but i does only get the help message.

**Comment by Sude-** [comment]
```--list-format``` only selects the formatting for ```--list```
```lgogdownloader --list --list-format j``` should do what you want

**Comment by Sude-** [comment]
Actually I should probably just combine the options so ```--list``` is also used for selecting the format.
I'll probably do that later today or tomorrow

**Comment by Sude-** [comment]
It turned out to be very simple change so I just pushed it in 9d188e7
```--list``` is now used to select the formatting so ```lgogdownloader --list j``` is what you want

**Comment by LuckyTurtleDev** [comment]
Thanks again. Works fine now.

> Actually I should probably just combine the options so --list is also used for selecting the format.

Yes, this is a much more intuitive.
