### ISSUE TITLE
check-orphans enhacements for autmatic removal

### ISSUE THREAD

**Issue by yourfate** [Sude-/lgogdownloader#243]
I use `--check-orphans` to clean my directories. My current approach is:

`lgogdownloader --check-orphans | xargs rm`

that is not really a good way to do this however, as all of the other output of lgogdownloader, such as the progress in checking, also ends up at `rm`.

There should be a way either have `--check-orphans` also delete the orphans, or to have it work with `--report` to create a file with the orphaned files, one per line, which I can then feed to `rm` to delete the files.

I have also tried `--verbosity -1` to see if it would get rid of any message other than the files, but no luck.

**Comment by ScarletEmerald** [comment]
Are you sure your current method is not working?  When I do this, the file paths go on stdout through the pipe, while the progress bar goes only on stderr to the terminal.

You could try `lgogdownloader --check-orphans | tee orphans.txt` to verify what is going to xargs.

**Comment by Sude-** [comment]
89724cd adds option to delete orphaned files.
Use ```lgogdownloader --check-orphans --delete-orphans``` to automatically delete orphaned files.
It will not ask for confirmation and will delete everything it determines to be orphaned.
So make sure to check the output of ```lgogdownloader --check-orphans``` before running it with ```--delete-orphans```
