### ISSUE TITLE
save-logo option is misleading

### ISSUE THREAD

**Issue by Samael-JJ** [Sude-/lgogdownloader#245]
What is downloaded by the save-logo option is more a low quality thumbnail than a real logo.

This option should be renamed save-thumbnail.

Anyway a real logo downloading option might be nice.

**Comment by BenjaminSchuermann** [comment]
Maybe get the images from gogdb under details -> Images
https://www.gogdb.org/product/1207659026#details

**Comment by Sude-** [comment]
Full size logo is downloaded as of 73d18dc

**Comment by Samael-JJ** [comment]
Great ! Thank you !
And thank you very much for this software !
