### ISSUE TITLE
"HTTP response code said error" and "basic_string: construction from null is not valid" abort at login

### ISSUE THREAD

**Issue by v-evets** [Sude-/lgogdownloader#278]
```
$ lgogdownloader --update-cache
Email: <redacted>
Password: 
HTTP response code said error
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
Aborted
```
Logging in with versions using the htmlcxx parser (i.e. < 3.13) using the same GOG credentials works just fine.

Gentoo Linux 2.15
lgogdownloader 3.14
htmltidy 5.8.0

**Comment by Eschguy** [comment]
Just got this as well

Fedora 40 
Kernel 6.10.5
lgogdownloader 3.14

**Comment by Sude-** [comment]
I'm guessing something goes wrong and the libtidy buffer is empty for some reason
b30515b should fix the crash
However if the buffer is empty then that means it will fail to get the login form for libcurl based login.
In that case the downloader should prompt for either gui or browser login.

**Comment by Eschguy** [comment]
I cleared my config and logged in again for good measure, can confirm #b30515b fixes it.

**Comment by v-evets** [comment]
3.15 looks pretty fixed to me :)
