### ISSUE TITLE
Error: std::length_error what(): basic_string::_M_replace

### ISSUE THREAD

**Issue by zahroc** [Sude-/lgogdownloader#279]
Getting the following error:

terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace
Aborted (core dumped)

using this command line on v3.14 under Ubuntu

lgogdownloader --download --report --directory /mnt/gog/downloads/windows --xml-directory /mnt/gog/xml/windows --platform windows --save-serials --save-logo --include all --exclude bl,dl,l --save-changelogs

it has been working fine for a long time

suggestions?

**Comment by Sude-** [comment]
Some more changes in 6556dc6

> forgive my ignorance, but how does one go about getting the fix and applying it?
> i normally download the release, build and run.
> that is the extent of my knowledge.

You can clone the repository with
```git clone https://github.com/Sude-/lgogdownloader.git```
and later pull any new changes with ```git pull```

Or you can download the zip archive that github provides
https://github.com/Sude-/lgogdownloader/archive/refs/heads/master.zip

and then build it just like the release version

**Comment by zahroc** [comment]
working now
