### ISSUE TITLE
[Feature Request] dump wishlist

### ISSUE THREAD

**Issue by shakeyourbunny** [Sude-/lgogdownloader#42]
It would be really neat, if lgogdownloader would list all games (not download, obviously) which are wishlisted (see https://www.gog.com/account/wishlist), eg

$ lgogdownloader --wishlist

produces:

1954 Alcatraz
Bird Story
Aarklash: Legacy
Agarest: Generations of War - Collector’s Edition
Anomaly Warzone Earth
...

**Comment by shakeyourbunny** [comment]
Any news on having time for this feature request?

**Comment by Sude-** [comment]
I added --wishlist option in 29e6b62
