### ISSUE TITLE
Save CD keys if present

### ISSUE THREAD

**Issue by ssokolow** [Sude-/lgogdownloader#43]
I use lgogdownloader to make sure I've got everything in my game backups in case GOG is ever forced to pull a game so thoroughly that it's removed from my account.

However, I still have to manually save any CD keys that may be present in the library expanders and that's awkward, error prone, and time-consuming. (especially given that the expanders close in response to a right-click)

If nothing else, LGOGDownloader should grab the expander body and save it, verbatim, in a file with a name like `cd_keys.html` (Though, ideally, I'd prefer to see it pared down to just the relevant bits and stored as `cd_keys.txt` instead)

**Comment by Sude-** [comment]
I added ```--save-serials``` option in 216cfae
It only saves the serials when running with ```--download```
It can be used with ```--list-details``` to show the serials in the output
When using ```--save-serials``` with ```--update-cache``` the serials are saved to the cache file

There doesn't seem to be a good way to determine which games have serials so using ```--save-serials``` makes the downloader try to find serials for all games.
