### ISSUE TITLE
"Found nothing in " .... during updating the cache

### ISSUE THREAD

**Issue by shakeyourbunny** [Sude-/lgogdownloader#47]
Is this related to the current ongoing unbundling of the GOG installer or a bug in lgogdownloader?

$ lgogdownloader --version
```
LGOGDownloader 2.21 git d978498
```

$ lgogdownloader --update-cache
( I inserted some blanks for better readability and censored the OAuth )
```
HTTP ERROR: 403 (https://api.gog.com/downloader2/game/interstate76/installer_win_en?oauth_consumer_key=1f)
Found nothing in https://api.gog.com/downloader2/game/interstate76/installer_win_en

HTTP ERROR: 403 (https://api.gog.com/downloader2/game/kings_quest_1_2_3/installer_win_en?oauth_consumer_key=1f)
Found nothing in https://api.gog.com/downloader2/game/kings_quest_1_2_3/installer_win_en

HTTP ERROR: 403 (https://api.gog.com/downloader2/game/kings_quest_4_5_6/installer_win_en?oauth_consumer_key=1f4)
Found nothing in https://api.gog.com/downloader2/game/kings_quest_4_5_6/installer_win_en

HTTP ERROR: 403 (https://api.gog.com/downloader2/game/m_a_x_m_a_x_2/installer_win_en?oauth_consumer_key=1f)
Found nothing in https://api.gog.com/downloader2/game/m_a_x_m_a_x_2/installer_win_en

HTTP ERROR: 403 (https://api.gog.com/downloader2/game/patrician_1_2/installer_win_en?oauth_consumer_key=1f)
Found nothing in https://api.gog.com/downloader2/game/patrician_1_2/installer_win_en

HTTP ERROR: 403 (https://api.gog.com/downloader2/game/the_penumbra_collection/installer_win_en?oauth_consumer_key=1f)
Found nothing in https://api.gog.com/downloader2/game/the_penumbra_collection/installer_win_en

HTTP ERROR: 403 (https://api.gog.com/downloader2/game/pirates_gold_plus/installer_win_en?oauth_consumer_key=1f4)
Found nothing in https://api.gog.com/downloader2/game/pirates_gold_plus/installer_win_en

HTTP ERROR: 403 (https://api.gog.com/downloader2/game/wallace_gromits_grand_adventures/installer_win_en?oauth_consumer_key=1f4)
Found nothing in https://api.gog.com/downloader2/game/wallace_gromits_grand_adventures/installer_win_en
Getting game info 649 / 649
```

All games are currently not unbundled and Wallace and Gromitt is a game which you cannot buy anymore. Other games seem to load fine.

**Comment by Sude-** [comment]
This is most likely related to unbundling the games. I was getting 403 errors when GOG unbundled the Tomb Raider games.
Try ```--list-details``` on of one of those games using debug build. The debug build tries to get the response when 403 error happens, it should tell you the reason for 403 error. When I was getting 403 errors because of unbundling, the response stated something about me not owning the game.

**Comment by shakeyourbunny** [comment]
Yes this "you do not came along

$ bin/Debug/lgogdownloader --list-details --game kings_quest
```
DEBUG INFO (API::getResponseOAuth)
URL: https://api.gog.com/downloader2/game/kings_quest_1_2_3/installer_win_en
DEBUG INFO (API::getResponse)
URL: https://api.gog.com/downloader2/game/kings_quest_1_2_3/installer_win_en?oauth_consumer_key=1f4
Response (CURLE_HTTP_RETURNED_ERROR):
<h1>403</h1>
<h2>Forbidden</h2>
array(2) {
  ["code"]=>
  int(0)
  ["message"]=>
  bool(false)
}
string(24) "you do not own this game"

DEBUG INFO (API::getResponseOAuth)
URL: https://api.gog.com/downloader2/game/kings_quest_4_5_6/installer_win_en
DEBUG INFO (API::getResponse)
URL: https://api.gog.com/downloader2/game/kings_quest_4_5_6/installer_win_en?oauth_consumer_key=1f..
Response (CURLE_HTTP_RETURNED_ERROR):
<h1>403</h1>
<h2>Forbidden</h2>
array(2) {
  ["code"]=>
  int(0)
  ["message"]=>
  bool(false)
}
string(24) "you do not own this game"
```

The interesting thing, though, is, that I just downloaded these King's Quest 1+2+3 and 4+5+6 installers through my library page without any issues.

http://cdn.gog.com/secure/kings_quest_123/pc/setup_kings_quest123_2.0.0.14.exe?1223fb438......c1f9&fileExtForIe=.exe (19 MB)
http://cdn.gog.com/secure/kings_quest_456/pc/setup_kings_quest456_2.0.0.16.exe?1223f....c79a27&fileExtForIe=.exe (295 MB)

So, I'm a bit puzzled, but I don't really think that it is lgogdownloader's fault and I'm going through my missing bundled downloads getting them, far far far far away from GOGs clutches.

**Comment by shakeyourbunny** [comment]
See 
http://www.gog.com/forum/general/important_notice_unbundling_games/post1652
