### ISSUE TITLE
Download hangs after forced 24h reconnect of ISP

### ISSUE THREAD

**Issue by Ghabry** [Sude-/lgogdownloader#50]
In Germany our biggest internet company "Telekom" has a "nice" feature called "Zwangstrennung". That means that after 24h they do a forced disconnect and give you a new IP address.

When this happens lgogdownloader just hangs with an output like
```
77% [===============     ] 2803.53/3645.88MB @ 0.00kB/s ETA: 24855d 03h 14m 07s
```
and must be ^C/-ed (SIGINT) and restarted (after restart the download continues at the position I stopped it, that's cool)

lgogdownloader runs unsupervised on my RasPi. So I usually see this hang when I get home and nothing downloaded for hours :(. No I can't try to avoid this because my internet connection is really slow and some downloads take ages to finish.

Would it be possible for lgogdownloader to detect when a download hangs and try to continue it?

**Comment by Sude-** [comment]
Does de301d7 help with this issue?

**Comment by Ghabry** [comment]
Output is now

```
Downloading: Windows Installer, German
/usr/local/hdd/data/GOG/[...]_2.0.0.9.exe
  5% [=                         ] 28.40/528.81MB @ 157.46kB/s ETA: 54m 14s
Retry 1/10 (timeout)
 65% [================          ] 345.10/528.81MB @ 1.48MB/s ETA: 2m 04s

```

Works perfect. Thank you :)
