### ISSUE TITLE
Parsing error? * Line 1, Column 1 Syntax error: value, object or array expected.

### ISSUE THREAD

**Issue by d7415** [Sude-/lgogdownloader#55]
On download/status I get the following message:
"* Line 1, Column 1
  Syntax error: value, object or array expected."

It worked fine at the start of the summer sale, but I noticed this problem yesterday using v2.23 and it continued when I changed to c4c2f8cb6de06c06792ddae0ce5b7bf08f5790cd.
Debug build shows all the game info is there in a massive block of JSON so it seems like a parsing error.

**Comment by huancz** [comment]
Not saying this is the same issue, but... I'm getting the same error message, until I run lgogdownloader --login (and supply credentials). Which lasts about an hour, after which I have to login again. Didn't try debug build yet, but you can see if it helps in your case.

**Comment by ssokolow** [comment]
I've been seeing the same problem for a while but didn't have time to diagnose and, since `--download-file` still works, I assumed it was a shelf-parsing bug.

**Comment by d7415** [comment]
--login seems to have fixed it for now. I had meant to try that, but when debug showed me a list of all my games I figured I had to be logged in! I won't close this just yet though as it sounds like more of a workaround than a fix.

**Comment by ssokolow** [comment]
My workaround is going to be updating my [lgogd_uri](https://github.com/ssokolow/lgogd_uri) frontend to acknowledge that GOG's new design added `gogdownloader://` links for the Linux versions, so I can use `--download-file` for everything rather than detecting non-extra links and converting them to `--download` regexes.

**Comment by Sude-** [comment]
In 84e8ab8 the downloader now assumes that failed JSON parsing in Downloader::getGames is caused by expired cookies and tells the user to try --login

Sometimes GOG seems to set the cookies to expire really soon.
There were some threads earlier about people getting logged out after a short time when using browser which I assume was caused by the cookies expiring. Can't find the threads now though because the forum search sucks on GOG.

You can check when the cookies are set to expire by using something like this after login
```
date -d@$(grep '[0-9]\+' ~/.config/lgogdownloader/cookies.txt | awk '{print $5}' | grep -v '^0$' | sort | head -1)
```

**Comment by ssokolow** [comment]
It's a major hassle to copy-paste my GOG username and password from my password manager every time lgogdownloader needs to re-login. Would it be possible for lgogdownloader to support saving a copy of the username and password for automatic re-login?

(Or do I have to jerry rig such a thing myself by wrapping lgogdownloader in a [pexpect](https://pexpect.readthedocs.org/en/latest/) script which embeds my username and password and calls lgogdownloader with --login before running it with the actual intended arguments?)

**Comment by d7415** [comment]
Looks like I misread that json block, so this was probably it. I'll close it.

**Comment by Sude-** [comment]
> It's a major hassle to copy-paste my GOG username and password from my password manager every time lgogdownloader needs to re-login. Would it be possible for lgogdownloader to support saving a copy of the username and password for automatic re-login?
> 
> (Or do I have to jerry rig such a thing myself by wrapping lgogdownloader in a pexpect script which embeds my username and password and calls lgogdownloader with --login before running it with the actual intended arguments?)

Here's a patch to add automatic login
https://sites.google.com/site/gogdownloader/autologin.diff

Create ```$XDG_CONFIG_HOME/lgogdownloader/autologin.cfg``` to use automatic login
```
{
	"email": "email_or_username",
	"password": "password"
}
```
Are there any issues with this patch?

**Comment by huancz** [comment]
I'm not sure autologin is such a good idea from security perspective, but as long as it stays optional...

There must be a way to obtain long-term token, Galaxy doesn't prompt me for password every time I boot my gaming console^W^W Windows PC. Maybe it just stores the username/password, but even browser doesn't require me to login when I allow gog.com cookies to last longer than for session. Even after long inactivity.

I guess sometimes it's just easier to work around the issue.

**Comment by ssokolow** [comment]
Sorry for the delay. I'm still making preparations for my last exam. I'll try to get that patch tested tonight.

**Comment by ssokolow** [comment]
It seems to be working. I'll let you know whether any problems show up while it's downloading the Trine: Enchanted Edition updates.

**Comment by ssokolow** [comment]
Nothing to complain about so far. The Windows installer and patch and the tarball downloaded without issue.

**Comment by huancz** [comment]
It appers that I have manged to fix this issue, without using autologin. I got tired looking through the mess, so I just deleted my cookie file completely and let lgogdownloader start again from clean state. There was lot of old/unused/most likely broken stuff in there, now there is only about half of them, they expire in a year and everything works like before. Lgogdownloader should probably do the same with --login, I doubt there is any information in there that should persist between logins.

**Comment by Sude-** [comment]
> It appers that I have manged to fix this issue, without using autologin. I got tired looking through the mess, so I just deleted my cookie file completely and let lgogdownloader start again from clean state. There was lot of old/unused/most likely broken stuff in there, now there is only about half of them, they expire in a year and everything works like before. Lgogdownloader should probably do the same with --login, I doubt there is any information in there that should persist between logins.

Old cookies are now deleted in 6e5a087
