### ISSUE TITLE
Compiling problems on slackware-current gcc ++ 4.92

### ISSUE THREAD

**Issue by shakeyourbunny** [Sude-/lgogdownloader#57]
Hi, 

I have some compiling problems with the current commit 9db2b8f2b0 .
OS is Slackware Linux Current, Compiler is GCC 4.92
Linux Kernel 3.10-7

It has some issues on building main.c, where it falls flat on basic IOlib. According to https://stackoverflow.com/questions/21138340/mismatched-c-header-versions it has something to do with the compiling command in the Makefile.

In file included from /usr/include/c++/4.9.2/i486-slackware-linux/bits/c++config.h:430:0,
                 from /usr/include/c++/4.9.2/iostream:38,
                 from include/config.h:10,
                 from include/downloader.h:24,
                 from main.cpp:7:
/usr/include/c++/4.9.2/i486-slackware-linux/bits/os_defines.h:44:19: error: missing binary operator before token "("
 #if __GLIBC_PREREQ(2,15) && defined(_GNU_SOURCE)
                   ^
In file included from /usr/include/c++/4.9.2/cwchar:44:0,
                 from /usr/include/c++/4.9.2/bits/postypes.h:40,
                 from /usr/include/c++/4.9.2/iosfwd:40,
                 from /usr/include/c++/4.9.2/ios:38,
                 from /usr/include/c++/4.9.2/ostream:38,
                 from /usr/include/c++/4.9.2/iostream:39,
                 from include/config.h:10,
                 from include/downloader.h:24,
                 from main.cpp:7:
/usr/include/wchar.h:74:43: error: missing binary operator before token "("
 # if defined __cplusplus && __GNUC_PREREQ (4, 4)

...

                          ^
In file included from /usr/include/libio.h:56:0,
                 from /usr/include/stdio.h:74,
                 from /usr/include/c++/4.9.2/cstdio:42,
                 from /usr/include/c++/4.9.2/ext/string_conversions.h:43,
                 from /usr/include/c++/4.9.2/bits/basic_string.h:2850,
                 from /usr/include/c++/4.9.2/string:52,
                 from /usr/include/c++/4.9.2/bits/locale_classes.h:40,
                 from /usr/include/c++/4.9.2/bits/ios_base.h:41,
                 from /usr/include/c++/4.9.2/ios:42,
                 from /usr/include/c++/4.9.2/ostream:38,
                 from /usr/include/c++/4.9.2/iostream:39,
                 from include/config.h:10,
                 from include/downloader.h:24,
                 from main.cpp:7:
/usr/include/stdio.h:942:1: error: expected declaration before '}' token
 __END_DECLS
 ^
make: *** [obj/Debug/main.o] Error 1

Full error log on Pastebin:
http://pastebin.com/raw.php?i=yfH48Ev4

**Comment by Sude-** [comment]
Do older versions compile or do they also give the same error?

**Comment by shakeyourbunny** [comment]
I traced the problem back to the json library.

Slackware does not have a package for the libjson, so I thought it would be this library:
http://slackbuilds.org/repository/14.1/libraries/jsoncpp/
(  Homepage: https://github.com/open-source-parsers/jsoncpp )

I guess it is the wrong library, but which one is the correct one lgogdownloader uses?

**Comment by Sude-** [comment]
That's the correct library
I'm guessing the issue is caused by this in the SlackBuild
```
# Move incude directory because it conflicts with json-c.
# This is how Arch, Fedora, Ubuntu and Gentoo do it.
[ -d $PKG/usr/include/json ] && mv $PKG/usr/include/json $PKG/usr/include/$PRGNAM
```
That statement isn't actually correct.
Debian and Ubuntu have json-c in /usr/include/json-c and jsoncpp in /usr/include/jsoncpp/json
Arch has json-c in /usr/include/json-c and jsoncpp in /usr/include/json

Because the include directory gets moved to /usr/include/jsoncpp it causes issue mentioned in the stackoverflow discussion.

You should be able to fix this by editing the SlackBuild so it uses /usr/include/jsoncpp/json
```
[ -d $PKG/usr/include/json ] && mv $PKG/usr/include/json $PKG/usr/include/$PRGNAM/json
```
or by making few changes to lgogdownloader
```
sed -i -e "s;<json/;<jsoncpp/;g" main.cpp src/*.cpp include/*.h
sed -i -e "s; -I/usr/include/jsoncpp;;" Makefile
```

**Comment by shakeyourbunny** [comment]
Did compile now after applying the latter sed modification to lgogdownloader and satisfying the other dependencies ... (rhash, your Makefile does not install the symlink for the library and the .a file *sigh*)

lgogdownloader compiles (and seeming to work now).

Thank you!
