### ISSUE TITLE
[feature suggestion] add more --list- options

### ISSUE THREAD

**Issue by vv221** [Sude-/lgogdownloader#58]
When we want to list only installers for a given game, we need to use something like --list-details --no-extras --no-patches --no-dlc
It would be nice to have more options like --list-installers, --list-extras, etc. that would list only one type of files for a given game.

**Comment by Sude-** [comment]
Easiest would be to add those as aliases for various ```--list-details --no-...``` options but I'm not sure if that is the best option. I'll see what I can do.

**Comment by vv221** [comment]
I don’t see any reason why this wouldn’t work.
But it means you’ll have to update these aliases each time you use a new --no-… option.

**Comment by bwrsandman** [comment]
You could use and `--include`, `--exclude` type configuration. For example:
```
# Show only installers
$ lgogdownloader --list-details --include installers
# Show only installers and patches
$ lgogdownloader --list-details --include installers,patches
# Show all but installers
$ lgogdownloader --list-details --exclude installers
# Show all but installers and patches
$ lgogdownloader --list-details --exclude installers,patches
# Conflict, --include takes precedence: show only patches
$ lgogdownloader --list-details --exclude installers --include=patches
# Conflict: Raise error or simply show nothing
$ lgogdownloader --list-details --exclude installers --include=installers
```

**Comment by vv221** [comment]
Don’t know how easy/hard it would be to implement, but I really like bwrsandman’s suggestion ;)
I think it would be very intuitive to use, and it would scale well with the eventual inclusion of new options.

**Comment by Sude-** [comment]
I think that changing the affected options to bit/flag field and then using ```--include``` , ```--exclude``` type configuration would probably work the best.

**Comment by Sude-** [comment]
3465384 now uses include/exclude options to select what to download/list/repair
My plan is to extend this later to allow selecting between base game and dlc installers/extras/etc but it requires some changes to Downloader class before it's possible

**Comment by a-detiste** [comment]
Hi @Sude- 

Can the new argument interface considered as stable & backward compatible from now ?

@skitt 

If so, can the current git master be packaged as a pre-release for Debian ?

> My plan is to extend this later to allow selecting between base game and dlc installers/extras/etc

The old games we are working one doens't provides DLC, so we don't need this.

**Comment by Sude-** [comment]
> Can the new argument interface considered as stable & backward compatible from now ?

It can be considered stable and backward compatible from now on.

I was planning on adding few options regarding DLCs and changing the current options a little before releasing version 2.26 but it turned out to be a much bigger task than I originally realized and thus I decided not to do it. I have few ideas on how I can make the changes later without it affecting the current options.

**Comment by a-detiste** [comment]
Thanks!

**Comment by vv221** [comment]
With the --include/--exclude options, I think we can consider this feature as done.
