### ISSUE TITLE
Cannot pass email/pw to lgogdownloader?

### ISSUE THREAD

**Issue by ProfessorKaos64** [Sude-/lgogdownloader#72]
It is possible to automate setting a password with passwd, and then unset the values to delete them. Is it not possible to pass values to lgogdownloader? The dev of VaporOS (SteamOS variant) and I are trying to make a zenity dialog [script tool](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/utilities/gog-downloader.sh) (that will become a package maybe) for users to download from GOG using this tool. The aim is to automate (in a more visual way for people) logging in, downloading, etc.

```
echo -ne "email@gmail.com\nPASSWORD" | lgogdownloader --login-api
```

Result:
```
Unable to read email and password
```

If it is trivial, can it be made to pass this to the native command?

```
lgogdownloader --login-adpi username password
```

**Comment by truh** [comment]
Seems like the reason login via pipes is failing is [line 135 in downloader.cpp](https://github.com/Sude-/lgogdownloader/blob/master/src/downloader.cpp#L135).

```c++
    if (!isatty(STDIN_FILENO)) {
        std::cerr << "Unable to read email and password" << std::endl;
        return 0;
    }
```

``!isatty(STDIN_FILENO)`` checks whether stdin is redirected. If it is the login function is aborted and the application terminated.

Is this intended behaviour or is there a different reason why this check is made?

**Comment by truh** [comment]
Looks like this check was first introduced with the commit 574a315c4444920e5fe64d429d1d3acf0dd74a84. Just removing the check won't work either because ``getpass(<string>)`` expects to get it's data from a terminal, not a pipe.

Good thing this is easy enough to work around with a short expect script. Expect will not only work with ``getpass`` but will also pass the ``isatty(STDIN_FILENO)`` check.

``` expect
expect << __EOF__
eval spawn "lgogdownloader --login";
expect "Email:";
send "<email>\n";
expect "Password:";
send "<password>\n";
expect "Login successful";
interact;
__EOF__
```

**Comment by a-detiste** [comment]
Great idea, I was used to patch (hardcode) my own user-id & password in compiled program, but this is better.

**Comment by ProfessorKaos64** [comment]
I tired on a new build today, `lgogdownloader --login` and my email and password failed.

**Comment by truh** [comment]
Is this specific to automated logins or does this happen when you try logging in manually as well?
A bug similar to the one you are experience seems to be documented in an existing issue: https://github.com/Sude-/lgogdownloader/issues/77

**Comment by ProfessorKaos64** [comment]
Yep, pretty much #77 is what I meant. I'll take my issue to that thread and close this. I hope this gets sorted out at some point. The lack of GOG Galaxy makes this tool extremely useful for gamers and tinkerers (I made packages for SteamOS). Thank you for the response.
