### ISSUE TITLE
Support multiple simultaneous downloads in parallel

### ISSUE THREAD

**Issue by boltronics** [Sude-/lgogdownloader#79]
I'm downloading at 247kB/s which is extremely slow and painful.

```
windows/fallout_tactics_classic/setup_fallout_tactics_2.1.0.12.exe
 81% ▕████████████████████▉     ▏ 1361.34/1686.55MB @ 247.37kB/s ETA: 22m 26s
```

For comparison, I regularly get 1.6MB/s through Steam.

Assuming GOG don't shape total downloads based on account or IP, it seems to me that lgogdownloader can help address this problem by adding support for downloading multiple files simultaneously.

**Comment by Sude-** [comment]
That is really slow. I usually get 8-10 MB/s from GOG.

Downloading multiple files in parallel requires rewriting the download logic and either multithreading the download logic or using curl_multi interface instead of curl_easy interface.

Rewriting the download logic has been on my todo list for a long time. This is something that I'd like to do at some point but I haven't had the time to really work on yet.
I experimented with libaria2 support for downloading some time ago to see how libaria2 works and how easy it would be to use. You could try using the experimental aria2 support to see if it works.

```
wget https://sites.google.com/site/gogdownloader/use_aria2.diff
patch -p1 < use_aria2.diff
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DWITH_ARIA2=1
make
```

By default it tries to use 10 connections to download the file.
You can change the behavior by changing the values for "max-connection-per-server", "min-split-size" and "split" options in src/downloader.cpp
However this patch isn't very well tested. There's a good chance that it crashes, doesn't work at all for you or does something unexpected.

**Comment by boltronics** [comment]
Thanks @Sude-, I'll give it a go (tonight, or otherwise hopefully sometime this week).

The weird thing I have since noticed is that when I run GOG Galaxy on the same system under Wine, I am easily able to max out my connection that way. It may be that GOG Galaxy is already doing parallel downloads in the background to achieve such speeds, but I'll have to investigate that further with netstat or a Wireshark.

**Comment by boltronics** [comment]
First I tried without the patch, and I was getting around 250Kb/s as expected.

Here's the results of running with the use_aria2.diff patch:
```
$ ./update.sh gnu_linux
Getting game info 53 / 53
Downloading: Linux Installer, English
gnu_linux/akalabeth_world_of_doom/gog_akalabeth_world_of_doom_2.0.0.3.sh
COMPLETE /media/installers/games/purchased/gog.com/boltronics/lgogdownloader/gnu_linux/akalabeth_world_of_doom/gog_akalabeth_world_of_doom_2.0.0.3.sh
./update.sh: line 3: 27856 Segmentation fault      /home/abolte/opt/lgogdownloader/bin/lgogdownloader --download --language 1 --platform linux --exclude extras --directory gnu_linux
$
```

Seemed to fail on the second file when the first file has already completed during a previous run. So for my next test I renamed /media/installers/games/purchased/gog.com/boltronics/lgogdownloader/gnu_linux/akalabeth_world_of_doom/gog_akalabeth_world_of_doom_2.0.0.3.sh out of the way and re-ran the script.

```
$ ./update.sh gnu_linux
Getting game info 53 / 53
Downloading: Linux Installer, English
gnu_linux/akalabeth_world_of_doom/gog_akalabeth_world_of_doom_2.0.0.3.sh
COMPLETE /media/installers/games/purchased/gog.com/boltronics/lgogdownloader/gnu_linux/akalabeth_world_of_doom/gog_akalabeth_world_of_doom_2.0.0.3.sh

Downloading cover gnu_linux/anomaly_warzone_earth/cover_0.png
COMPLETE /media/installers/games/purchased/gog.com/boltronics/lgogdownloader/gnu_linux/anomaly_warzone_earth/cover_0.png.1

Downloading: Linux Installer, English
gnu_linux/anomaly_warzone_earth/gog_anomaly_warzone_earth_2.0.0.2.sh
COMPLETE /media/installers/games/purchased/gog.com/boltronics/lgogdownloader/gnu_linux/anomaly_warzone_earth/gog_anomaly_warzone_earth_2.0.0.2.sh
./update.sh: line 3: 27967 Segmentation fault      /home/abolte/opt/lgogdownloader/bin/lgogdownloader --download --language 1 --platform linux --exclude extras --directory gnu_linux
$  
```

As expected, this time it did attempt to download gog_akalabeth_world_of_doom_2.0.0.3.sh, and it did so much much quicker! I also compared the checksum of the old and new gog_akalabeth_world_of_doom_2.0.0.3.sh files, and they matched.

I ran the test a second time, and then the speed was back to being quite slow once more. A bit odd. So I tried yet again, and it was still back to being slow! Really weird.

Next I deleted my build and went back to the Debian testing (stretch) packaged lgogdownloader version I was using before 2.27-1, and suddenly I was getting 1.5MB+/s. I couldn't believe it! I didn't change anything, so it seemed to be down to luck!

One theory I had was that the mirror must have a load balancer where one of the app nodes is slow or overloaded, and I usually keep hitting it. It would explain why I don't see similar behaviour in Steam and elsewhere, but then again that doesn't explain consistently good performance in Galaxy.

Lastly, I hit Ctrl-c and re-ran the command one more time. This time, my speed was back to sucking again, this time at around 150Kb/s - worse than before.

Again, I don't see this issue with the Galaxy client running under Wine (and I also tried that again tonight to confirm that's still true). Is it possible lgogdownloader has some built-in shaping or prioritisation that might not be working properly under some circumstances?

**Comment by Sude-** [comment]
I forgot to post this patch here earlier.

Here's a patch to add parallel downloads
https://sites.google.com/site/gogdownloader/multithreaded_download_v1.diff

Use ```--threads``` option to set how many parallel downloads you want to run. The default is 4 threads.

There are some changes in the behavior of downloader:
- Serials and changelogs are saved and covers downloaded for all games that match the "--game" filter before any other files are downloaded.
- Automatic XML creation is run after all files are downloaded. Previously xml data was automatically created right after a download finished.
- The "--limit-rate" option sets rate limit for thread not global rate limit. So if you have 4 threads and set "--limit-rate" to 100 then each thread has a rate limit of 100 meaning that global limit is 400.
